<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Car|Rental Landingpage</title>

  <!-- Bootstrap -->
  <link href="../assets/css/bootstrap.min.css" rel="stylesheet">

  <!-- Bootstrap -->
  <link href="../assets/css/animate.css" rel="stylesheet">

  <!-- Google Font Lato -->
  <link href='http://fonts.googleapis.com/css?family=Lato:400,700,900,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="../assets/css/font-awesome.min.css">

  <!-- Plugin Styles -->
  <link href="../assets/css/datepicker.css" rel="stylesheet">


  <!-- Main Styles -->
  <link href="../assets/css/styles.css" rel="stylesheet">
  <!-- Available main styles: styles-red.css, styles-green.css -->

    <style>
        form .website_hp{
            display: none;
        }
    </style>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <link href="css/ie8fix.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Lato:400' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:900' rel='stylesheet' type='text/css'>
    <![endif]-->


    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/img/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/img/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/img/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/img/ico/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="../assets/img/ico/favicon.png">
  </head>
  <body id="top" data-spy="scroll" data-target=".navbar" data-offset="260">

  <!-- Header start -->
  <header data-spy="affix" data-offset-top="39" data-offset-bottom="0" class="large">

      <div class="row container box">
          <div class="col-md-5">
              <!-- Logo start -->
              <div class="brand">
                  <h1><a class="scroll-to" href="#top"><img class="img-responsive" src="../assets/img/logo.gif" alt="Car|Rental"></a></h1>
              </div>
              <!-- Logo end -->
          </div>

          <div class="col-md-7">
              <div class="pull-right">
                  <div class="header-info pull-right">
                      <div class="contact pull-left">CONTACT: (562) 498-4600</div>
                      <!-- Language Switch start -->
                      <div class="language-switch pull-right">
                          <div class="dropdown">
                              <a data-toggle="dropdown" href="#" id="language-switch-dropdown">Select your language </a>
                              <ul class="dropdown-menu" role="menu" aria-labelledby="language-switch-dropdown">
                                  <li><a href="#"><img src="../assets/img/flags/United-States.png" alt="usa"> English</a></li>
                                  <li><a href="#"><img src="../assets/img/flags/Germany.png" alt="germany"> German</a></li>
                                  <li><a href="#"><img src="../assets/img/flags/France.png" alt="france"> French</a></li>
                              </ul>
                          </div>
                      </div>
                      <!-- Language Switch end -->
                  </div>
              </div>

              <div class="clearfix"></div>

              <!-- start navigation -->
              <nav class="navbar navbar-default" role="navigation">
                  <div class="container-fluid">
                      <!-- Toggle get grouped for better mobile display -->
                      <div class="navbar-header">
                          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                              <span class="sr-only">Toggle navigation</span>
                              <span class="icon-bar"></span>
                              <span class="icon-bar"></span>
                              <span class="icon-bar"></span>
                          </button>
                          <a class="navbar-brand scroll-to" href="#top"><img class="img-responsive"  src="../assets/img/logo.gif" alt="Car|Rental"></a>
                      </div>
                      <!-- Collect the nav links, for toggling -->
                      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                          <!-- Nav-Links start -->
                          <ul class="nav navbar-nav navbar-right">
                              <li class="active"><a href="#top" class="scroll-to">Home</a></li>
                              <li><a href="#services" class="scroll-to">Services</a></li>
                              <li><a href="#vehicles" class="scroll-to">Vehicle Models</a></li>
                              <li class="dropdown">
                                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Blog <span class="caret"></span></a>
                                  <ul class="dropdown-menu" role="menu">
                                      <li><a href="/blog-posts">Blog Posts</a></li>
                                      <li><a href="/blog-single-post">Blog Single Post</a></li>
                                      <li><a href="/error404">Error 404</a></li>
                                  </ul>
                              </li>
                              <li><a href="#locations" class="scroll-to">Locations</a></li>
                              <li><a href="#contact" class="scroll-to">Contact</a></li>
                          </ul>
                          <!-- Nav-Links end -->
                      </div>
                  </div>
              </nav>
              <!-- end navigation -->
          </div>
      </div>

  </header>
  <!-- Header end -->



    <!-- Teaser start -->
    <section id="teaser">
      <div class="container">
        <div class="row">
          <div class="col-md-7 col-xs-12 pull-right">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
              <!-- Wrapper for slides start -->
              <div class="carousel-inner">
                <div class="item active">
                  <h1 class="title">Luxury car from from $28 day
                    <span class="subtitle">Treat yourself in USA</span></h1>
                    <div class="car-img">
                      <img src="../assets/img/car1.png" class="img-responsive" alt="car1">
                    </div>
                  </div>
                  <div class="item">
                    <h1 class="title">Get 15% off your rental
                      <span class="subtitle">Plan your trip now</span></h1>
                      <div class="car-img">
                        <img src="../assets/img/car2.png" class="img-responsive" alt="car1">
                      </div>
                    </div>
                  </div>
                  <!-- Wrapper for slides end -->

                  <!-- Slider Controls start -->
                  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                  </a>
                  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                  </a>
                  <!-- Slider Controls end -->
                </div>
              </div>
              <div class="col-md-5 col-xs-12 pull-left">
                <div class="reservation-form-shadow">
                    <form action="/create" method="post" name="car-select-form" id="car-select-form">

                        <div class="alert alert-danger hidden" id="car-select-form-msg">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            <strong>Note:</strong> All fields required!
                        </div>

                        <!-- Car select start -->
                        <div class="styled-select-car">
                            <select name="car-select" id="car-select">
                                <option value="">Select your car type</option>

                                <?php foreach ($items as $item): ?>

                                    <option value="<?=$item['id']?>"
                                            data-car-image="<?=$item['image']?>">

                                        <?=$item['name']?>

                                    </option>

                                <?php endforeach; ?>

                            </select>
                        </div>
                        <!-- Car select end -->

                        <!-- Pick-up location start -->
                        <div class="location">
                            <div class="input-group pick-up">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-map-marker"></span> Pick-up</span>
                                <input type="text" name="pick-up-location" id="pick-up-location" class="form-control autocomplete-location" placeholder="Enter a City or Airport">
                            </div>
                            <!-- Pick-up location end -->

                            <a class="different-drop-off" href="#">Need a different drop-off location?</a>

                            <!-- Drop-off location start -->
                            <div class="input-group drop-off">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-map-marker"></span> Drop-off</span>
                                <input type="text" name="drop-off-location" id="drop-off-location" class="form-control autocomplete-location" placeholder="Enter a City or Airport">
                            </div>
                        </div>
                        <!-- Drop-off location end -->

                        <!-- Pick-up date/time start -->
                        <div class="datetime pick-up">
                            <div class="date pull-left">
                                <div class="input-group">
                                    <span class="input-group-addon pixelfix"><span class="glyphicon glyphicon-calendar"></span> Pick-up</span>
                                    <input type="text" readonly="true" name="pick-up-date" id="pick-up-date" class="form-control datepicker" placeholder="mm/dd/yyyy">
                                </div>
                            </div>
                            <div class="time pull-right">
                                <div class="styled-select-time">
                                    <select name="pick-up-time" id="pick-up-time">
                                        <option value="1:00">1:00</option>
                                        <option value="2:00">2:00</option>
                                        <option value="3:00">3:00</option>
                                        <option value="4:00">4:00</option>
                                        <option value="5:00">5:00</option>
                                        <option value="6:00">6:00</option>
                                        <option value="7:00">7:00</option>
                                        <option value="8:00">8:00</option>
                                        <option value="9:00">9:00</option>
                                        <option value="10:00">10:00</option>
                                        <option value="11:00">11:00</option>
                                        <option value="12:00">12:00</option>
                                        <option value="13:00">13:00</option>
                                        <option value="14:00">14:00</option>
                                        <option value="15:00">15:00</option>
                                        <option value="16:00">16:00</option>
                                        <option value="17:00">17:00</option>
                                        <option value="18:00">18:00</option>
                                        <option value="19:00">19:00</option>
                                        <option value="20:00">20:00</option>
                                        <option value="21:00">21:00</option>
                                        <option value="22:00">22:00</option>
                                        <option value="23:00">23:00</option>
                                        <option value="24:00">24:00</option>
                                    </select>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <!-- Pick-up date/time end -->

                        <!-- Drop-off date/time start -->
                        <div class="datetime drop-off">
                            <div class="date pull-left">
                                <div class="input-group">
                                    <span class="input-group-addon pixelfix"><span class="glyphicon glyphicon-calendar"></span> Drop-off</span>
                                    <input type="text" readonly="true" name="drop-off-date" id="drop-off-date" class="form-control datepicker" placeholder="mm/dd/yyyy">
                                </div>
                            </div>
                            <div class="time pull-right">
                                <div class="styled-select-time">
                                    <select name="drop-off-time" id="drop-off-time">
                                        <option value="1:00">1:00</option>
                                        <option value="2:00">2:00</option>
                                        <option value="3:00">3:00</option>
                                        <option value="4:00">4:00</option>
                                        <option value="5:00">5:00</option>
                                        <option value="6:00">6:00</option>
                                        <option value="7:00">7:00</option>
                                        <option value="8:00">8:00</option>
                                        <option value="9:00">9:00</option>
                                        <option value="10:00">10:00</option>
                                        <option value="11:00">11:00</option>
                                        <option value="12:00">12:00</option>
                                        <option value="13:00">13:00</option>
                                        <option value="14:00">14:00</option>
                                        <option value="15:00">15:00</option>
                                        <option value="16:00">16:00</option>
                                        <option value="17:00">17:00</option>
                                        <option value="18:00">18:00</option>
                                        <option value="19:00">19:00</option>
                                        <option value="20:00">20:00</option>
                                        <option value="21:00">21:00</option>
                                        <option value="22:00">22:00</option>
                                        <option value="23:00">23:00</option>
                                        <option value="24:00">24:00</option>
                                    </select>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <!-- Drop-off date/time end -->

                        <input type="submit" class="submit" name="submit" value="continue car reservation" id="checkoutModalLabel">
                    </form>
                </div>
              </div>

            </div>
          </div>
        </section>
        <div class="arrow-down"></div>
        <!-- Teaser end -->



        <!-- Services start -->
        <section id="services" class="container">
          <div class="row">
            <div class="col-md-12 title">
              <h2>Customer Services</h2>
              <span class="underline">&nbsp;</span>
            </div>

            <!-- Service Box start -->
            <div class="col-md-6">
              <div class="service-box wow fadeInLeft" data-wow-offset="100">
                <div class="service-icon">+</div>
                <h3 class="service-title">Special rates on car booking</h3>
                <div class="clearfix"></div>
                <p class="service-content">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed  nonumy eirmod tempor invidunt ut labore et dolore magnaed aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren.</p>
              </div>
            </div>
            <!-- Service Box end -->

            <!-- Service Box start -->
            <div class="col-md-6">
              <div class="service-box wow fadeInRight" data-wow-offset="100">
                <div class="service-icon">+</div>
                <h3 class="service-title">Mobile Phone Reservation</h3>
                <div class="clearfix"></div>
                <p class="service-content">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed  nonumy eirmod tempor invidunt ut labore et dolore magnaed aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren.</p>
              </div>
            </div>
            <!-- Service Box end -->

            <!-- Service Box start -->
            <div class="col-md-6">
              <div class="service-box wow fadeInLeft" data-wow-offset="100">
                <div class="service-icon">+</div>
                <h3 class="service-title">Unlimited Miles Car Rental</h3>
                <div class="clearfix"></div>
                <p class="service-content">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed  nonumy eirmod tempor invidunt ut labore et dolore magnaed aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren.</p>
              </div>
            </div>
            <!-- Service Box end -->

            <!-- Service Box start -->
            <div class="col-md-6">
              <div class="service-box wow fadeInRight" data-wow-offset="100">
                <div class="service-icon">+</div>
                <h3 class="service-title">One Way Car Rentals</h3>
                <div class="clearfix"></div>
                <p class="service-content">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed  nonumy eirmod tempor invidunt ut labore et dolore magnaed aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren.</p>
              </div>
            </div>
            <!-- Service Box end -->

          </div>
        </section>
        <!-- Services end -->



        <!-- Newsletter start -->
        <section id="newsletter" class="wow slideInLeft" data-wow-offset="300">
          <div class="container">
            <div class="row">
              <div class="col-md-12"><div class="alert hidden" id="newsletter-form-msg"></div></div>
              <div class="col-md-5 col-xs-12">
                <h2 class="title">Sign up for amazing offers
                  <span class="subtitle">exclusive access for offers and promotions</span></h2>
                </div>
                <div class="col-md-7">
                  <div class="newsletter-form pull-left">
                    <form action="#" method="post" name="newsletter-form" id="newsletter-form">
                        <input type="hidden" name="action" value="send_newsletter_form"/>
                        <input type="text" class="website_hp" name="website_hp"/>
                      <div class="input-group">
                        <input type="email" name="newsletter-email" class="form-control" placeholder="Enter your Email Address">
                        <span class="input-group-btn">
                          <input class="btn btn-default button" type="submit" value="send">
                        </span>
                      </div>
                    </form>
                  </div>
                  <div class="social-icons pull-right">
                    <ul>
                      <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
                      <li><a class="googleplus" href="#"><i class="fa fa-google-plus"></i></a></li>
                      <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
                    </ul>
                  </div>
                  <div class="clearfix"></div>
                </div>
              </div>
            </div>
          </section>
          <!-- Newsletter end -->



          <!-- Vehicles start -->
          <section id="vehicles" class="container">
            <div class="row">
              <div class="col-md-12">
                <h2 class="title wow fadeInDown" data-wow-offset="200">Vehicle Models - <span class="subtitle">Our rental fleet at a glance</span></h2>
              </div>

              <!-- Vehicle nav start -->
              <div class="col-md-3 vehicle-nav-row wow fadeInUp" data-wow-offset="100">
                <div id="vehicle-nav-container">
                  <ul class="vehicle-nav">
                    <?php foreach ($items as $item):?>
                       <li class="active"><a href="#<?=$item['id']?>"><?=$item['name']?></a><span class="active"></span></li>
                    <?php endforeach;?>
                  </ul>
                </div>


              </div>
              <!-- Vehicle nav end -->

              <!-- Vehicle 1 data start -->
                <?php foreach ($items as $item) : ?>
                <div class="vehicle-data" id="<?=$item['id']?>">
                <div class="col-md-6 wow fadeIn" data-wow-offset="100">
                  <div class="vehicle-img">
                    <img class="img-responsive" src="<?=$item['image']?>" width="500" height="285" alt="Vehicle">
                  </div>
                </div>
                <div class="col-md-3 wow fadeInUp" data-wow-offset="200">
                  <div class="vehicle-price"><?=$item['price']?> <span class="info">rent per day</span></div>
                  <table class="table vehicle-features">
                    <tr>
                      <td>Model</td>
                      <td><?=$item['model']?></td>
                    </tr>
                    <tr>
                      <td>Doors</td>
                      <td><?=$item['doors']?></td>
                    </tr>
                    <tr>
                      <td>Seats</td>
                      <td><?=$item['seats']?></td>
                    </tr>
                    <tr>
                      <td>Luggage</td>
                      <td><?=$item['luggage']?></td>
                    </tr>
                    <tr>
                      <td>Transmission</td>
                      <td><?=$item['transmission']?></td>
                    </tr>
                    <tr>
                      <td>Air conditioning</td>
                      <td><?=$item['conditioner']?></td>
                    </tr>
                    <tr>
                      <td>Year</td>
                      <td><?=$item['year']?></td>
                    </tr>
                  </table>
                  <a href="#teaser" class="reserve-button scroll-to"><span class="glyphicon glyphicon-calendar"></span> Reserve now</a>
                </div>
              </div>
                <?php endforeach; ?>
              <!-- Vehicle 1 data end -->

            </div>
          </section>
          <!-- Vehicles end -->



          <!-- Reviews start -->
          <section id="reviews" class="container wow fadeInUp">
            <div class="row text-center">
              <div class="col-md-12 stars">
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star big"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
              </div>
              <div class="col-md-10 col-md-offset-1">
                <div id="reviews-carousel" class="carousel slide carousel-fade" data-ride="carousel">
                  <div class="carousel-inner">

                      <!-- Review item 2 start -->
                      <?php foreach ($reviews as $review) : ?>
                          <div class="item">
                              <div class="review">
                                  <?=$review['text']?>
                              </div>
                              <div class="author">
                                  <?=$review['name']?>
                              </div>
                          </div>
                      <?php endforeach; ?>
                      <!-- Review item 2 end -->
                </div>

                <!-- Review Nav start -->
                <ol class="carousel-indicators">
                  <li data-target="#reviews-carousel" data-slide-to="0" class="active"></li>
                  <li data-target="#reviews-carousel" data-slide-to="1"></li>
                  <li data-target="#reviews-carousel" data-slide-to="2"></li>
                </ol>
                <!-- Review Nav end -->

              </div>
            </div>
          </div>
        </section>
        <!-- Reviews end -->



        <!-- Locations start -->
        <section id="locations">
          <div class="container location-select-container wow bounceInDown" data-wow-offset="200">
            <div class="row">
              <div class="col-md-8 col-md-offset-2">
                <div class="location-select">
                  <div class="row">
                    <div class="col-md-6">
                      <h2>Car Rental Locations</h2>
                    </div>
                    <div class="col-md-6">
                      <div class="styled-select-location">
                        <select id="location-map-select">
                            <option>улица Пушкина 30</option>
                            <option>улица Маршала Жукова 45</option>
                            <option>улица Крылова 88</option>
                            <option>Щетинкина 69</option>
                            <option>проспект Ленина 6</option>
                        </select>
                      </div>
                    </div>

                  </div>
                </div>
              </div>
            </div>
            <div class="arrow-down-location">&nbsp;</div>
          </div>
          <div class="map wow bounceInUp" data-wow-offset="100" >
              <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2360.884706217731!2d91.46233437719273!3d53.72031624667572!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x5d2c22a3aeddbfc3%3A0x108577c44236df0d!2z0YPQuy4g0J_Rg9GI0LrQuNC90LAsIDMwLCDQkNCx0LDQutCw0L0sINCg0LXRgdC_LiDQpdCw0LrQsNGB0LjRjywgNjU1MDEy!5e0!3m2!1sru!2sru!4v1700723217399!5m2!1sru!2sru" width="600%" height="100%" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
          </div>

        </section>
        <!-- Locations end -->



        <!-- Information start -->
        <section id="information" class="container">

          <!-- Single photo start -->
          <div class="row wow fadeInLeft" data-wow-offset="100">
            <div class="col-md-6 col-xs-12 pull-right">
              <img src="../assets/img/info-img.jpg" alt="Info Img" class="img-responsive">
            </div>
            <div class="col-md-6 pull-left">
              <h2 class="title">Quality Guaranteed</h2>
              <h3 class="subtitle">Here is an example with one single photo displayed on the right.</h3>
              <p>Here is some dummy text. <span class="my-tooltip" data-toggle="tooltip" title="" data-original-title="This is an demo tooltip!">Hover over me!</span> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde, vero voluptas delectus explicabo maxime ad qui incidunt! Saepe.</p>
              <a href="http://themeforest.net/item/car-rental-landing-page/8245093?ref=themeinjection" class="btn">More information</a>
              <a href="http://themeforest.net/item/car-rental-landing-page/8245093?ref=themeinjection" class="btn btn-gray">Buy this theme</a>
            </div>
          </div>
          <!-- Single photo end -->

          <!-- Video start -->
          <div class="row wow fadeInRight" data-wow-offset="50">
            <div class="col-md-6">
              <div class="video">
                <!-- Youtube iframe start -->
                <iframe width="420" height="315" src="//www.youtube.com/embed/9_5pjZlWV3A?rel=0&autoplay=0" allowfullscreen></iframe>
                <!-- Youtube iframe end -->
              </div>
            </div>
            <div class="col-md-6">
              <h2 class="title">Watch our info tour</h2>
              <h3 class="subtitle">You can also show youtube videos in this section!</h3>
              <p>Here is some dummy text. Lorem ipsum dolor sit amet, <span class="label label-default">This is an labeled text snippet!</span>, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde, vero voluptas delectus explicabo maxime ad qui incidunt! no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
            </div>
          </div>
          <!-- Video end -->

        </section>
        <!-- Information end -->



        <!-- Partners start -->
        <section id="partners" class="wow fadeIn" data-wow-offset="50">
          <div class="container">
            <div class="row">
              <div class="col-md-12 text-center">
                <h2>Meet Our Partners</h2>
                <span class="underline">&nbsp;</span>
                <p>To contribute to positive change and achieve our sustainability goals, we partner with many extraordinary organizations around the world. Their expertise enables us to do far more than we could alone, and their passion and talent inspire us. It is our pleasure to introduce you to a handful of the organizations whose accomplishments and commitments are representative of all the organizations we are fortunate to call our partners.</p>
              </div>
              <div class="col-md-3 col-xs-6 text-center">
                <img src="../assets/img/partner1.png" alt="Partner" class="img-responsive wow fadeInUp" data-wow-delay="0.5s" data-wow-offset="200">
              </div>
              <div class="col-md-3 col-xs-6 text-center">
                <img src="../assets/img/partner2.png" alt="Partner" class="img-responsive wow fadeInUp" data-wow-delay="1s" data-wow-offset="200">
              </div>
              <div class="col-md-3 col-xs-6 text-center">
                <img src="../assets/img/partner3.png" alt="Partner" class="img-responsive wow fadeInUp" data-wow-delay="1.5s" data-wow-offset="200">
              </div>
              <div class="col-md-3 col-xs-6 text-center">
                <img src="../assets/img/partner4.png" alt="Partner" class="img-responsive wow fadeInUp" data-wow-delay="2s" data-wow-offset="200">
              </div>
            </div>
          </div>
        </section>
        <!-- Partners end -->



        <!-- Contact start -->
        <section id="contact" class="container wow bounceInUp" data-wow-offset="50">
          <div class="row">
            <div class="col-md-12">
              <h2>Contact Us</h2>
            </div>
            <div class="col-md-4 col-xs-12 pull-right">
              <h4 class="contact-box-title">Customer Center</h4>
              <div class="contact-box">
                <img src="../assets/img/contact-box-img1.jpg" alt="contact-img">
                <div class="contact-box-name">Sarah Connor</div>
                <div class="contact-box-phon"><span class="highlight">Phone:</span> 666-999-888</div>
                <div class="contact-box-email"><span class="highlight">Email:</span> connor@example.com</div>
                <div class="clearfix"></div>
              </div>
              <div class="contact-box-border">&nbsp;</div>

              <div class="contact-box-divider">&nbsp;</div>

              <h4 class="contact-box-title">Change or Cancel Reservation</h4>
              <div class="contact-box">
                <img src="../assets/img/contact-box-img2.jpg" alt="contact-img">
                <div class="contact-box-name">Mike Smith</div>
                <div class="contact-box-phon"><span class="highlight">Phone:</span> 666-999-888</div>
                <div class="contact-box-email"><span class="highlight">Email:</span> connor@example.com</div>
                <div class="clearfix"></div>
              </div>
              <div class="contact-box-border">&nbsp;</div>

              <div class="contact-box">
                <img src="../assets/img/contact-box-img3.jpg" alt="contact-img">
                <div class="contact-box-name">Jane Doe</div>
                <div class="contact-box-phon"><span class="highlight">Phone:</span> 666-999-888</div>
                <div class="contact-box-email"><span class="highlight">Email:</span> connor@example.com</div>
                <div class="clearfix"></div>
              </div>
              <div class="contact-box-border">&nbsp;</div>
            </div>
            <div class="col-md-8 col-xs-12 pull-left">
              <p class="contact-info">You have any questions or need additional information? <br>
                <span class="address"><span class="highlight">Address:</span>  Car|Rental / 3861 Sepulveda Blvd. / Culver City, CA 90230</span></p>
                <form action="/feedback" method="post" id="contact-form" name="contact-form">
                    <input type="hidden" name="action" value="send_contact_form"/>
                    <input type="text" class="website_hp" name="website_hp"/>

                  <div class="alert hidden" id="contact-form-msg"></div>

                  <div class="form-group">
                    <input type="text" class="form-control first-name text-field" name="first-name" placeholder="First Name:">
                    <input type="text" class="form-control last-name text-field" name="last-name" placeholder="Last Name:">
                    <div class="clearfix"></div>
                  </div>

                  <div class="form-group">
                    <input type="tel" class="form-control telephone text-field" name="telephone" placeholder="Telephone:">
                  </div>

                  <div class="form-group">
                    <input type="email" class="form-control email text-field" name="email" placeholder="Email:">
                  </div>

                  <div class="form-group">
                    <textarea class="form-control message" name="message" placeholder="Message:"></textarea>
                  </div>

                    <p class="contact-info" id="contact-info_notification" hidden></p>

                    <input type="submit" class="btn submit-message" name="submit-message" value="Submit Message">


                </form>
              </div>

            </div>
          </section>
          <!-- Contact end -->


          <a href="#" class="scrollup">ScrollUp</a>


          <!-- Footer start -->
          <footer>
            <div class="container">
              <div class="row">
                <div class="col-md-12 text-center">
                  <ul class="footer-nav">
                    <li><a class="scroll-to" href="#top">Home</a></li>
                    <li><a class="scroll-to" href="#services">Service</a></li>
                    <li><a class="scroll-to" href="#vehicles">Vehicle Models</a></li>
                    <li><a class="scroll-to" href="#reviews">Reviews</a></li>
                    <li><a class="scroll-to" href="#locations">Locations</a></li>
                    <li><a class="scroll-to" href="#contact">Contact</a></li>
                  </ul>
                  <div class="clearfix"></div>
                  <p class="copyright">©2014 Themeinjection, All Rights Reserved</p>
                </div>
              </div>
            </div>
          </footer>
          <!-- Footer end -->



          <!-- Checkout Modal Start -->
          <div class="modal fade" id="checkoutModal" tabindex="-1" role="dialog" aria-labelledby="checkoutModalLabel" aria-hidden="true" data-backdrop="static">
            <div class="modal-dialog">
              <div class="modal-content">
                <form action="/create" method="post" id="checkout-form" name="checkout-form">
                    <input type="hidden" name="action" value="send_inquiry_form"/>
                    <input type="text" class="website_hp" name="website_hp"/>

                  <!-- Modal header start -->
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Complete reservation</h4>
                  </div>
                  <!-- Modal header end -->

                  <!-- Modal body start -->
                  <div class="modal-body">

                    <!-- Checkout Info start -->
                    <div class="checkout-info-box">
                      <h3><i class="fa fa-info-circle"></i> Upon completing this reservation enquiry, you will receive::</h3>
                      <p>Your rental voucher to produce on arrival at the rental desk and a toll-free customer support number.</p>
                    </div>
                    <!-- Checkout Info end -->

                    <!-- Checkout Rental Info start -->
                    <div class="checkout-vehicle-info">
                      <div class="location-date-info">
                        <h3>Location & Date</h3>
                        <div class="info-box">
                          <span class="glyphicon glyphicon-calendar"></span>
                          <h4 class="info-box-title">Pick-Up Time</h4>
                          <p class="info-box-description"><span id="pick-up-date-ph"></span> at <span id="pick-up-time-ph"></span></p>
                          <input type="hidden" name="pick-up" id="pick-up" value="">
                        </div>
                        <div class="info-box">
                          <span class="glyphicon glyphicon-calendar"></span>
                          <h4 class="info-box-title">Drop-Off Time</h4>
                          <p class="info-box-description"><span id="drop-off-date-ph"></span> at <span id="drop-off-time-ph"></span></p>
                          <input type="hidden" name="drop-off" id="drop-off" value="">
                        </div>
                        <div class="info-box">
                          <span class="glyphicon glyphicon-map-marker"></span>
                          <h4 class="info-box-title">Pick-Up Location</h4>
                          <p class="info-box-description" id="pickup-location-ph"></p>
                          <input type="hidden" name="pickup-location" id="pickup-location" value="">
                        </div>
                        <div class="info-box">
                          <span class="glyphicon glyphicon-map-marker"></span>
                          <h4 class="info-box-title">Drop-Off Location</h4>
                          <p class="info-box-description" id="dropoff-location-ph"></p>
                          <input type="hidden" name="dropoff-location" id="dropoff-location" value="">
                        </div>
                      </div>

                      <div class="vehicle-info">
                        <h3>CAR: <span id="selected-car-ph"></span></h3> <a href="#vehicles" class="scroll-to">[ Vehicle Models ]</a>
                        <input type="hidden" name="selected-car" id="selected-car" value="">
                        <div class="clearfix"></div>
                        <div class="vehicle-image">
                            <img class="img-responsive" id="selected-vehicle-image" src="" alt="Vehicle">
                        </div>
                      </div>

                      <div class="clearfix"></div>

                    </div>
                    <!-- Checkout Rental Info end -->

                    <hr>

                    <!-- Checkout Personal Info start -->
                    <div class="checkout-personal-info">
                      <div class="alert hidden" id="checkout-form-msg">
                        test
                      </div>
                      <h3>PERSONAL INFORMATION</h3>
                      <div class="form-group left">
                        <label for="first-name">First Name:</label>
                        <input type="text" class="form-control" name="first-name" id="first-name" placeholder="Enter your first name">
                      </div>
                      <div class="form-group right">
                        <label for="last-name">Last Name:</label>
                        <input type="text" class="form-control" name="last-name" id="last-name" placeholder="Enter your last name">
                      </div>
                      <div class="form-group left">
                        <label for="phone-number">Phone Number:</label>
                        <input type="text" class="form-control" name="phone-number" id="phone-number" placeholder="Enter your phone number">
                      </div>
                      <div class="form-group right age">
                        <label for="age">Age:</label>
                        <div class="styled-select-age">
                          <select name="age" id="age">
                          <option value="18">18</option>
                           <option value="19">19</option>
                           <option value="20">20</option>
                           <option value="21">21</option>
                           <option value="22">22</option>
                           <option value="23">23</option>
                           <option value="24">24</option>
                           <option value="25">25</option>
                           <option value="26">26</option>
                           <option value="27">27</option>
                           <option value="28">28</option>
                           <option value="29">29</option>
                           <option value="30">30</option>
                           <option value="31">31</option>
                           <option value="32">32</option>
                           <option value="33">33</option>
                           <option value="34">34</option>
                           <option value="35">35</option>
                           <option value="36">36</option>
                           <option value="37">37</option>
                           <option value="38">38</option>
                           <option value="39">39</option>
                           <option value="40">40</option>
                           <option value="41">41</option>
                           <option value="42">42</option>
                           <option value="43">43</option>
                           <option value="44">44</option>
                           <option value="45">45</option>
                           <option value="46">46</option>
                           <option value="47">47</option>
                           <option value="48">48</option>
                           <option value="49">49</option>
                           <option value="50">50</option>
                           <option value="51">51</option>
                           <option value="52">52</option>
                           <option value="53">53</option>
                           <option value="54">54</option>
                           <option value="55">55</option>
                           <option value="56">56</option>
                           <option value="57">57</option>
                           <option value="58">58</option>
                           <option value="59">59</option>
                           <option value="50">50</option>
                           <option value="61">61</option>
                           <option value="62">62</option>
                           <option value="63">63</option>
                           <option value="64">64</option>
                           <option value="65">65</option>
                           <option value="66">66</option>
                           <option value="67">67</option>
                           <option value="68">68</option>
                           <option value="69">69</option>
                           <option value="70">70</option>
                           <option value="71">71</option>
                           <option value="72">72</option>
                           <option value="73">73</option>
                           <option value="74">74</option>
                           <option value="75">75</option>
                           <option value="76">76</option>
                           <option value="77">77</option>
                           <option value="78">78</option>
                           <option value="79">79</option>
                           <option value="80">80</option>
                           <option value="81">81</option>
                           <option value="82">82</option>
                           <option value="83">83</option>
                           <option value="84">84</option>
                           <option value="85">85</option>
                           <option value="86">86</option>
                           <option value="87">87</option>
                           <option value="88">88</option>
                           <option value="89">89</option>
                           <option value="90">90</option>
                           <option value="91">91</option>
                           <option value="92">92</option>
                           <option value="93">93</option>
                           <option value="94">94</option>
                           <option value="95">95</option>
                           <option value="96">96</option>
                           <option value="97">97</option>
                           <option value="98">98</option>
                           <option value="99">99</option>
                           <option value="100">100</option>
                         </select>
                       </div>
                     </div>
                     <div class="form-group left">
                      <label for="email-address">Email Address:</label>
                      <input type="email" class="form-control" name="email-address" id="email-address" placeholder="Enter your email address">
                    </div>
                    <div class="clearfix"></div>
                  </div>
                  <!-- Checkout Personal Info end -->

                  <!-- Checkout Address Info start -->
                  <div class="checkout-address-info">
                    <div class="clearfix"></div>
                  </div>
                  <!-- Checkout Address Info end -->

                  <div class="newsletter">
                    <div class="form-group">
                      <div class="checkbox">
                        <input id="check1" type="checkbox" name="newsletter" value="yes">
                        <label for="check1">Please send me latest news and updates</label>
                      </div>
                    </div>

                  </div>
                </div>
                <!-- Modal body end -->

                <!-- Modal footer start -->
                <div class="modal-footer">
                  <span class="btn-border btn-gray">
                    <button type="button" class="btn btn-default btn-gray" data-dismiss="modal">Cancel</button>
                  </span>
                  <span class="btn-border btn-yellow">
                    <button type="submit" class="btn btn-primary btn-yellow">Reserve now</button>
                  </span>
                </div>
                <!-- Modal footer end -->

              </form>
            </div>
          </div>
        </div>
        <!-- Checkout Modal end -->


        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="../assets/js/jquery-1.11.0.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->

        <script src="../assets/js/bootstrap.min.js"></script>
        <script src="../assets/js/jquery.autocomplete.min.js"></script>
        <script src="../assets/js/jquery.placeholder.js"></script>
        <script src="../assets/js/locations-autocomplete.js"></script>
        <script src="../assets/js/bootstrap-datepicker.js"></script>
<!--        <script src="../assets/js/gmap3.min.js"></script>-->
<!--        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBsr1sFUtzPoVl9GIKmp1dXCS04tcJ9NfI" type="text/javascript"></script>-->





        <!--[if !(gte IE 8)]><!-->
            <script src="../assets/js/wow.min.js"></script>
            <script>
                // Initialize WOW
                //-------------------------------------------------------------
                new WOW({mobile: false}).init();
            </script>
        <!--<![endif]-->

        <script src="../assets/js/custom.js"></script>



      </body>
      </html>
